#!/bin/bash

# Global
mkdir outputs
INPUT_DIR="inputs/"
OUTPUT_DIR="outputs/"
FILE_TYPE=".txt"

CMD="wc -l"
INPUT_FILE1="gb01"
OUTPUT_FILE="wc-l-yw"
PY_COMB="./s_wc.py"
cat "${INPUT_DIR}${INPUT_FILE1}${FILE_TYPE}" | $CMD >"${OUTPUT_DIR}${OUTPUT_FILE}-seq${FILE_TYPE}"
cat "${INPUT_DIR}${INPUT_FILE1}-1${FILE_TYPE}" | $CMD >"${OUTPUT_DIR}${OUTPUT_FILE}-1${FILE_TYPE}"
cat "${INPUT_DIR}${INPUT_FILE1}-2${FILE_TYPE}" | $CMD >"${OUTPUT_DIR}${OUTPUT_FILE}-2${FILE_TYPE}"
${PY_COMB} "${OUTPUT_DIR}${OUTPUT_FILE}-1${FILE_TYPE}" "${OUTPUT_DIR}${OUTPUT_FILE}-2${FILE_TYPE}" >"${OUTPUT_DIR}${OUTPUT_FILE}-par${FILE_TYPE}"
